version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "service-a"
        LoadBalancerInfo:
          ContainerName: "service-b"
          ContainerPort: 8081
